# Generated by Django 5.0.3 on 2024-03-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pinjambuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=30)),
                ('Judul_buku', models.CharField(max_length=30)),
                ('Pengarang', models.CharField(max_length=30)),
                ('Tanggal_peminjaman', models.DateField()),
                ('Alamat', models.TextField()),
                ('Tanggal_pengembalian', models.DateField()),
            ],
        ),
    ]
